os: osx
language: swift
# macOS images: https://docs.travis-ci.com/user/reference/osx#macos-version
osx_image: xcode11.5

before_install:
  - brew tap bazelbuild/tap
  - brew install bazelbuild/tap/bazel

script:
  - bazel version
  - bazel build //:tulsi
  - bazel test //src/TulsiGeneratorTests --test_output=errors --nocheck_visibility
  - bazel test //src/TulsiGeneratorIntegrationTests --test_output=errors --nocheck_visibility
